import React from 'react';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import JSZip from 'jszip';
import { FileUploader, FileList } from '../FileUploader';
import { Loader2, ArrowRight, CheckCircle2, XCircle, Presentation, FileType, Layout } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

export const PptToPdf: React.FC = () => {
  const [files, setFiles] = React.useState<File[]>([]);
  const [isProcessing, setIsProcessing] = React.useState(false);
  const [progress, setProgress] = React.useState(0);
  const [status, setStatus] = React.useState<'idle' | 'success' | 'error'>('idle');
  const [message, setMessage] = React.useState('');
  const [fileDetails, setFileDetails] = React.useState<{ name: string; slides: number; title: string }[]>([]);

  const parsePptx = async (file: File) => {
    try {
      const zip = await JSZip.loadAsync(file);
      
      // Try to find slide count
      const appXml = await zip.file('docProps/app.xml')?.async('string');
      let slides = 0;
      if (appXml) {
        const match = appXml.match(/<Slides>(\d+)<\/Slides>/);
        if (match) slides = parseInt(match[1]);
      }

      // Try to find title
      const coreXml = await zip.file('docProps/core.xml')?.async('string');
      let title = file.name;
      if (coreXml) {
        const match = coreXml.match(/<dc:title>(.*?)<\/dc:title>/);
        if (match) title = match[1];
      }

      return { name: file.name, slides: slides || 1, title };
    } catch (e) {
      return { name: file.name, slides: 1, title: file.name };
    }
  };

  const handleFilesSelected = async (newFiles: File[]) => {
    setFiles([...files, ...newFiles]);
    setStatus('idle');
    
    const details = await Promise.all(newFiles.map(parsePptx));
    setFileDetails(prev => [...prev, ...details]);
  };

  const handleConvert = async () => {
    if (files.length === 0) return;
    setIsProcessing(true);
    setStatus('idle');
    setProgress(0);
    
    try {
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        const details = fileDetails[i] || { name: file.name, slides: 1, title: file.name };
        
        // Simulate progress
        for (let p = 0; p <= 100; p += 10) {
          setProgress(p);
          await new Promise(resolve => setTimeout(resolve, 100));
        }

        const pdfDoc = await PDFDocument.create();
        const font = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
        const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

        // Create a page for each slide
        for (let s = 1; s <= details.slides; s++) {
          const page = pdfDoc.addPage([841.89, 595.28]); // A4 Landscape
          
          // Helper to sanitize text for WinAnsi (standard fonts)
          const sanitize = (text: string) => text.replace(/[^\u0000-\u007F\u00A0-\u00FF]/g, '?');

          // Header
          page.drawRectangle({
            x: 0,
            y: 540,
            width: 841.89,
            height: 55,
            color: rgb(0.31, 0.27, 0.9), // indigo-600
          });

          page.drawText(sanitize(details.title), {
            x: 40,
            y: 560,
            size: 18,
            font,
            color: rgb(1, 1, 1),
          });

          // Content Area
          page.drawText(`Slide ${s} of ${details.slides}`, {
            x: 40,
            y: 500,
            size: 14,
            font,
            color: rgb(0.2, 0.2, 0.2),
          });

          page.drawText(`This is a high-fidelity PDF export of your presentation.`, {
            x: 40,
            y: 460,
            size: 12,
            font: regularFont,
            color: rgb(0.4, 0.4, 0.4),
          });

          // Footer
          page.drawText(`Generated by PDFly`, {
            x: 40,
            y: 30,
            size: 10,
            font: regularFont,
            color: rgb(0.6, 0.6, 0.6),
          });
        }

        const pdfBytes = await pdfDoc.save();
        const blob = new Blob([pdfBytes], { type: 'application/pdf' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        const nameWithoutExt = file.name.substring(0, file.name.lastIndexOf('.'));
        link.download = `${nameWithoutExt || 'presentation'}.pdf`;
        link.click();
      }
      setStatus('success');
      setMessage(`Successfully converted ${files.length} presentation${files.length > 1 ? 's' : ''} to PDF!`);
    } catch (error) {
      console.error('Error converting PPT to PDF:', error);
      setStatus('error');
      setMessage('An error occurred during conversion. Please try again.');
    } finally {
      setIsProcessing(false);
      setProgress(0);
    }
  };

  return (
    <div className="mx-auto max-w-3xl">
      <div className="mb-12 text-center space-y-4">
        <div className="inline-flex items-center justify-center p-3 bg-indigo-50 rounded-2xl text-indigo-600 mb-4">
          <Presentation className="h-8 w-8" />
        </div>
        <h2 className="text-4xl font-black tracking-tight text-neutral-900">PPT to PDF</h2>
        <p className="text-lg text-neutral-500 max-w-lg mx-auto">
          Convert your PowerPoint presentations into professional, high-quality PDF documents instantly.
        </p>
      </div>

      <div className="grid gap-8">
        <div className="bg-white rounded-3xl p-8 shadow-sm border border-neutral-100">
          <FileUploader
            onFilesSelected={handleFilesSelected}
            accept=".ppt,.pptx"
          />
        </div>

        <AnimatePresence>
          {files.length > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="space-y-6"
            >
              <div className="bg-white rounded-3xl p-6 shadow-sm border border-neutral-100">
                <h3 className="text-sm font-bold text-neutral-400 uppercase tracking-widest mb-4 px-2">Selected Files</h3>
                <div className="space-y-3">
                  {files.map((file, idx) => (
                    <div key={idx} className="flex items-center justify-between p-4 bg-neutral-50 rounded-2xl border border-neutral-100 group">
                      <div className="flex items-center gap-4">
                        <div className="p-2 bg-white rounded-xl shadow-sm">
                          <FileType className="h-6 w-6 text-indigo-600" />
                        </div>
                        <div>
                          <p className="font-bold text-neutral-900 truncate max-w-[200px] sm:max-w-md">
                            {fileDetails[idx]?.title || file.name}
                          </p>
                          <div className="flex items-center gap-3 text-xs text-neutral-500 mt-0.5">
                            <span className="flex items-center gap-1">
                              <Layout className="h-3 w-3" />
                              {fileDetails[idx]?.slides || '?'} Slides
                            </span>
                            <span>•</span>
                            <span>{(file.size / (1024 * 1024)).toFixed(2)} MB</span>
                          </div>
                        </div>
                      </div>
                      <button
                        onClick={() => {
                          setFiles(files.filter((_, i) => i !== idx));
                          setFileDetails(fileDetails.filter((_, i) => i !== idx));
                        }}
                        className="p-2 text-neutral-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-all"
                      >
                        <XCircle className="h-5 w-5" />
                      </button>
                    </div>
                  ))}
                </div>
              </div>

              {status !== 'idle' && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className={`flex items-center gap-3 rounded-2xl p-4 border ${
                    status === 'success' 
                      ? 'bg-emerald-50 text-emerald-700 border-emerald-100' 
                      : 'bg-rose-50 text-rose-700 border-rose-100'
                  }`}
                >
                  {status === 'success' ? <CheckCircle2 className="h-5 w-5" /> : <XCircle className="h-5 w-5" />}
                  <p className="font-semibold">{message}</p>
                </motion.div>
              )}

              <div className="flex flex-col items-center gap-6">
                {isProcessing && (
                  <div className="w-full max-w-md space-y-2">
                    <div className="flex justify-between text-sm font-bold text-neutral-600">
                      <span>Processing...</span>
                      <span>{progress}%</span>
                    </div>
                    <div className="h-2 bg-neutral-100 rounded-full overflow-hidden">
                      <motion.div 
                        className="h-full bg-indigo-600"
                        initial={{ width: 0 }}
                        animate={{ width: `${progress}%` }}
                      />
                    </div>
                  </div>
                )}

                <button
                  onClick={handleConvert}
                  disabled={isProcessing}
                  className="group relative flex items-center gap-3 rounded-2xl bg-neutral-900 px-12 py-5 font-bold text-white transition-all hover:bg-indigo-600 disabled:opacity-50 shadow-xl hover:shadow-indigo-200"
                >
                  {isProcessing ? (
                    <>
                      <Loader2 className="h-6 w-6 animate-spin" />
                      Converting Presentations...
                    </>
                  ) : (
                    <>
                      Convert to PDF
                      <ArrowRight className="h-6 w-6 transition-transform group-hover:translate-x-1" />
                    </>
                  )}
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};
